version: '3'
services:
  
  elasticsearch:
    image: "elasticsearch:7.1.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node 
  
  kibana: 
    image: "kibana:7.1.0"
    ports:
      - "5601:5601"
networks:
  default:
    external:
      name: some-network

